### ISSUE TITLE
About Input Dataset for Pretrain

### ISSUE THREAD

**Issue by loretoparisi** [gantheory/rl-playlist-generation#1]
Hello, according to the reference paper the first step is about  to generate baseline playlists based on the preferences of users about songs. Now assumed that the paper makes use of KKBox dataset, while here the dataset format has been specified, where shall I put `user_id` for each `song_id` i.e. the user listening?

Thank you.

**Comment by shunyaoshih** [comment]
Thank for your attention to this work! In this repo, I did not include the part of generating baseline playlists since it is not the major contribution. You can generate your own ones by related works listed in the paper. If you have any further questions, feel free to contact with me.
