### ISSUE TITLE
About Embedding and Vocabulary

### ISSUE THREAD

**Issue by loretoparisi** [gantheory/rl-playlist-generation#2]
The data util script makes use of a vocabulary file that is created started from the `raw_dat.txt` (`[date_of_created_playlist] [song_id1] [song_id2]...` format) file. Is that correct?
And what about creating embedding? How shall I extract it from the song info?
According to the paper 

> With the users and songs graph, we can
> calculate embedding features of songs and thus obtain the
> baseline playlist for each songs by finding their k-nearest
> neighbors. 

Does this mean that I can use low-level or high-level song features? Maybe the spectrum?

Thank you.

**Comment by shunyaoshih** [comment]
I think there are some misunderstandings and it might be related to [this issue](https://github.com/gantheory/rl-playlist-generation/issues/1) (I will update `README.md` according to these issues).

For the last two questions, yes. After you calculate embedding features from the graph, you can concatenate other features to those embeddings as the input of the model (No matter low-level, high-level, or even spectrum).
